import { Router } from 'express';
import authRoutes from './authRoutes.js';
import contactRoutes from './contactRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import orderRoutes from './orderRoutes.js';
import newsletterRoutes from './newsletterRoutes.js';
import serviceRoutes from './serviceRoutes.js';
import blogRoutes from './blogRoutes.js';
import menuRoutes from './menuRoutes.js';
import packageRoutes from './packageRoutes.js';
import userRoutes from './userRoutes.js';
import galleryRoutes from './galleryRoutes.js';
import uploadRoutes from './uploadRoutes.js';
import testimonialRoutes from './testimonialRoutes.js';
import faqRoutes from './faqRoutes.js';
import chatRoutes from './chatRoutes.js';
import commentRoutes from './commentRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import geminiRoutes from './geminiRoutes.js';
import chatbotBookingRoutes from './chatbotBookingRoutes.js';
import projectRoutes from './projectRoutes.js';
import teamRoutes from './teamRoutes.js';
import utilityRoutes from './utilityRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/contacts', contactRoutes);
router.use('/bookings', bookingRoutes);
router.use('/orders', orderRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/services', serviceRoutes);
router.use('/blogs', blogRoutes);
router.use('/menu', menuRoutes);
router.use('/packages', packageRoutes);
router.use('/users', userRoutes);
router.use('/gallery', galleryRoutes);
router.use('/upload', uploadRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/faqs', faqRoutes);
router.use('/chat', chatRoutes);
router.use('/comments', commentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/gemini', geminiRoutes);
router.use('/chatbot', chatbotBookingRoutes);
router.use('/projects', projectRoutes);
router.use('/team', teamRoutes);
router.use('/', utilityRoutes);

export default router;
